services:
  frontend:
    build: .
    ports:
      - "8087:8087"
    environment:
      BACKEND_URL: http://backend:${SERVER_PORT}/api/v1
      DATASOURCE_URL: ${DATASOURCE_URL}
      DB_PASSWORD: ${PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      SLACK_TOKEN: ${SLACK_TOKEN}